framework:
    rate_limiter:
        # define 2 rate limiters (one for username+IP, the other for IP)
        username_ip_login:
            policy: token_bucket
            limit: 5
            rate: { interval: "5 minutes" }

        ip_login:
            policy: sliding_window
            limit: 50
            interval: "15 minutes"

services:
    # our custom login rate limiter
    app.login_rate_limiter:
        class: Symfony\Component\Security\Http\RateLimiter\DefaultLoginRateLimiter
        arguments:
            # globalFactory is the limiter for IP
            $globalFactory: "@limiter.ip_login"
            # localFactory is the limiter for username+IP
            $localFactory: "@limiter.username_ip_login"

security:
    # Enables the new Symfony Security system based on Authenticators, all used authenticators must support this before enabling this.
    enable_authenticator_manager: true
    access_decision_manager:
        strategy: affirmative
        service: ~
        allow_if_all_abstain: false
        allow_if_equal_granted_denied: true
    encoders:
        App\Entity\User: bcrypt

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: app_user_provider
            lazy: true
            login_throttling:
                limiter: app.login_rate_limiter
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            logout:
                path: app_logout
                target: /
            entry_point: App\Security\AuthenticationEntryPoint

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_ADMIN }
